mod_name = "GrindingYourGears"
mod_id = "grinding_your_gears"
mod_group = "com.theendercore"
mod_version = "1.0.0"
mod_description = "Got spare gear? Well not any more!"
github_repo = "theendercore/GrindingYourGears"
discord_invite = "https://discord.gg/KZ5Q364hEg"
authors = [ "TheEnderCore" ]
license = "MIT"
version_range = ">=1.21.11 <26.1"
